/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPackagesRouteImport } from './routes/app/packages'
import { Route as AppRoutersRouteImport } from './routes/app/routers'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTicketsRouteImport } from './routes/app/tickets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutersRoute = AppRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/import': typeof AppImportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/routers': typeof AppRoutersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/import': typeof AppImportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/routers': typeof AppRoutersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/import': typeof AppImportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/routers': typeof AppRoutersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/billing'
    | '/app/customers'
    | '/app/import'
    | '/app/notifications'
    | '/app/packages'
    | '/app/routers'
    | '/app/services'
    | '/app/settings'
    | '/app/tickets'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/billing'
    | '/app/customers'
    | '/app/import'
    | '/app/notifications'
    | '/app/packages'
    | '/app/routers'
    | '/app/services'
    | '/app/settings'
    | '/app/tickets'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/billing'
    | '/app/customers'
    | '/app/import'
    | '/app/notifications'
    | '/app/packages'
    | '/app/routers'
    | '/app/services'
    | '/app/settings'
    | '/app/tickets'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routers': {
      id: '/app/routers'
      path: '/routers'
      fullPath: '/app/routers'
      preLoaderRoute: typeof AppRoutersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppImportRoute: typeof AppImportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppRoutersRoute: typeof AppRoutersRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppImportRoute: AppImportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppRoutersRoute: AppRoutersRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
