/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ResellerRouteImport } from './routes/reseller'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAcsRouteImport } from './routes/app/acs'
import { Route as AppAiRouteImport } from './routes/app/ai'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppFieldRouteImport } from './routes/app/field'
import { Route as AppHotspotRouteImport } from './routes/app/hotspot'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPackagesRouteImport } from './routes/app/packages'
import { Route as AppPartnersRouteImport } from './routes/app/partners'
import { Route as AppRadiusRouteImport } from './routes/app/radius'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppRoutersRouteImport } from './routes/app/routers'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppStatementsRouteImport } from './routes/app/statements'
import { Route as AppTicketsRouteImport } from './routes/app/tickets'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ResellerIndexRouteImport } from './routes/reseller/index'
import { Route as ApiAgentAckRouteImport } from './routes/api/agent/ack'
import { Route as ApiAgentHeartbeatRouteImport } from './routes/api/agent/heartbeat'
import { Route as ApiAgentPullRouteImport } from './routes/api/agent/pull'
import { Route as ApiAgentScriptRouteImport } from './routes/api/agent/script'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1CronBillingRouteImport } from './routes/api/v1/cron/billing'
import { Route as ApiWebhooksKopokopoSlugRouteImport } from './routes/api/webhooks/kopokopo/$slug'
import { Route as ApiWebhooksMpesaSlugRouteImport } from './routes/api/webhooks/mpesa/$slug'
import { Route as ApiV1RadiusAccountingSlugRouteImport } from './routes/api/v1/radius/accounting.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerRoute = ResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcsRoute = AppAcsRouteImport.update({
  id: '/acs',
  path: '/acs',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRoute,
} as any)
const AppHotspotRoute = AppHotspotRouteImport.update({
  id: '/hotspot',
  path: '/hotspot',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppRadiusRoute = AppRadiusRouteImport.update({
  id: '/radius',
  path: '/radius',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutersRoute = AppRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ResellerIndexRoute = ResellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResellerRoute,
} as any)
const ApiAgentAckRoute = ApiAgentAckRouteImport.update({
  id: '/api/agent/ack',
  path: '/api/agent/ack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHeartbeatRoute = ApiAgentHeartbeatRouteImport.update({
  id: '/api/agent/heartbeat',
  path: '/api/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPullRoute = ApiAgentPullRouteImport.update({
  id: '/api/agent/pull',
  path: '/api/agent/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentScriptRoute = ApiAgentScriptRouteImport.update({
  id: '/api/agent/script',
  path: '/api/agent/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CronBillingRoute = ApiV1CronBillingRouteImport.update({
  id: '/api/v1/cron/billing',
  path: '/api/v1/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksKopokopoSlugRoute = ApiWebhooksKopokopoSlugRouteImport.update({
  id: '/api/webhooks/kopokopo/$slug',
  path: '/api/webhooks/kopokopo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMpesaSlugRoute = ApiWebhooksMpesaSlugRouteImport.update({
  id: '/api/webhooks/mpesa/$slug',
  path: '/api/webhooks/mpesa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RadiusAccountingSlugRoute =
  ApiV1RadiusAccountingSlugRouteImport.update({
    id: '/api/v1/radius/accounting/$slug',
    path: '/api/v1/radius/accounting/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reseller': typeof ResellerRouteWithChildren
  '/app/acs': typeof AppAcsRoute
  '/app/ai': typeof AppAiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/field': typeof AppFieldRoute
  '/app/hotspot': typeof AppHotspotRoute
  '/app/import': typeof AppImportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/radius': typeof AppRadiusRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routers': typeof AppRoutersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/reseller/': typeof ResellerIndexRoute
  '/api/agent/ack': typeof ApiAgentAckRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/pull': typeof ApiAgentPullRoute
  '/api/agent/script': typeof ApiAgentScriptRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/cron/billing': typeof ApiV1CronBillingRoute
  '/api/webhooks/kopokopo/$slug': typeof ApiWebhooksKopokopoSlugRoute
  '/api/webhooks/mpesa/$slug': typeof ApiWebhooksMpesaSlugRoute
  '/api/v1/radius/accounting/$slug': typeof ApiV1RadiusAccountingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/acs': typeof AppAcsRoute
  '/app/ai': typeof AppAiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/field': typeof AppFieldRoute
  '/app/hotspot': typeof AppHotspotRoute
  '/app/import': typeof AppImportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/radius': typeof AppRadiusRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routers': typeof AppRoutersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/reseller': typeof ResellerIndexRoute
  '/api/agent/ack': typeof ApiAgentAckRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/pull': typeof ApiAgentPullRoute
  '/api/agent/script': typeof ApiAgentScriptRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/cron/billing': typeof ApiV1CronBillingRoute
  '/api/webhooks/kopokopo/$slug': typeof ApiWebhooksKopokopoSlugRoute
  '/api/webhooks/mpesa/$slug': typeof ApiWebhooksMpesaSlugRoute
  '/api/v1/radius/accounting/$slug': typeof ApiV1RadiusAccountingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reseller': typeof ResellerRouteWithChildren
  '/app/acs': typeof AppAcsRoute
  '/app/ai': typeof AppAiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/field': typeof AppFieldRoute
  '/app/hotspot': typeof AppHotspotRoute
  '/app/import': typeof AppImportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/radius': typeof AppRadiusRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routers': typeof AppRoutersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/reseller/': typeof ResellerIndexRoute
  '/api/agent/ack': typeof ApiAgentAckRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/pull': typeof ApiAgentPullRoute
  '/api/agent/script': typeof ApiAgentScriptRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/cron/billing': typeof ApiV1CronBillingRoute
  '/api/webhooks/kopokopo/$slug': typeof ApiWebhooksKopokopoSlugRoute
  '/api/webhooks/mpesa/$slug': typeof ApiWebhooksMpesaSlugRoute
  '/api/v1/radius/accounting/$slug': typeof ApiV1RadiusAccountingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/portal'
    | '/reseller'
    | '/app/acs'
    | '/app/ai'
    | '/app/billing'
    | '/app/customers'
    | '/app/field'
    | '/app/hotspot'
    | '/app/import'
    | '/app/notifications'
    | '/app/packages'
    | '/app/partners'
    | '/app/radius'
    | '/app/reports'
    | '/app/routers'
    | '/app/services'
    | '/app/settings'
    | '/app/statements'
    | '/app/tickets'
    | '/app/'
    | '/portal/'
    | '/reseller/'
    | '/api/agent/ack'
    | '/api/agent/heartbeat'
    | '/api/agent/pull'
    | '/api/agent/script'
    | '/api/auth/$'
    | '/api/v1/health'
    | '/api/v1/cron/billing'
    | '/api/webhooks/kopokopo/$slug'
    | '/api/webhooks/mpesa/$slug'
    | '/api/v1/radius/accounting/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/acs'
    | '/app/ai'
    | '/app/billing'
    | '/app/customers'
    | '/app/field'
    | '/app/hotspot'
    | '/app/import'
    | '/app/notifications'
    | '/app/packages'
    | '/app/partners'
    | '/app/radius'
    | '/app/reports'
    | '/app/routers'
    | '/app/services'
    | '/app/settings'
    | '/app/statements'
    | '/app/tickets'
    | '/app'
    | '/portal'
    | '/reseller'
    | '/api/agent/ack'
    | '/api/agent/heartbeat'
    | '/api/agent/pull'
    | '/api/agent/script'
    | '/api/auth/$'
    | '/api/v1/health'
    | '/api/v1/cron/billing'
    | '/api/webhooks/kopokopo/$slug'
    | '/api/webhooks/mpesa/$slug'
    | '/api/v1/radius/accounting/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/portal'
    | '/reseller'
    | '/app/acs'
    | '/app/ai'
    | '/app/billing'
    | '/app/customers'
    | '/app/field'
    | '/app/hotspot'
    | '/app/import'
    | '/app/notifications'
    | '/app/packages'
    | '/app/partners'
    | '/app/radius'
    | '/app/reports'
    | '/app/routers'
    | '/app/services'
    | '/app/settings'
    | '/app/statements'
    | '/app/tickets'
    | '/app/'
    | '/portal/'
    | '/reseller/'
    | '/api/agent/ack'
    | '/api/agent/heartbeat'
    | '/api/agent/pull'
    | '/api/agent/script'
    | '/api/auth/$'
    | '/api/v1/health'
    | '/api/v1/cron/billing'
    | '/api/webhooks/kopokopo/$slug'
    | '/api/webhooks/mpesa/$slug'
    | '/api/v1/radius/accounting/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResellerRoute: typeof ResellerRouteWithChildren
  ApiAgentAckRoute: typeof ApiAgentAckRoute
  ApiAgentHeartbeatRoute: typeof ApiAgentHeartbeatRoute
  ApiAgentPullRoute: typeof ApiAgentPullRoute
  ApiAgentScriptRoute: typeof ApiAgentScriptRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1CronBillingRoute: typeof ApiV1CronBillingRoute
  ApiWebhooksKopokopoSlugRoute: typeof ApiWebhooksKopokopoSlugRoute
  ApiWebhooksMpesaSlugRoute: typeof ApiWebhooksMpesaSlugRoute
  ApiV1RadiusAccountingSlugRoute: typeof ApiV1RadiusAccountingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller': {
      id: '/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof ResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/acs': {
      id: '/app/acs'
      path: '/acs'
      fullPath: '/app/acs'
      preLoaderRoute: typeof AppAcsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/field': {
      id: '/app/field'
      path: '/field'
      fullPath: '/app/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hotspot': {
      id: '/app/hotspot'
      path: '/hotspot'
      fullPath: '/app/hotspot'
      preLoaderRoute: typeof AppHotspotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partners': {
      id: '/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/radius': {
      id: '/app/radius'
      path: '/radius'
      fullPath: '/app/radius'
      preLoaderRoute: typeof AppRadiusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routers': {
      id: '/app/routers'
      path: '/routers'
      fullPath: '/app/routers'
      preLoaderRoute: typeof AppRoutersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/statements': {
      id: '/app/statements'
      path: '/statements'
      fullPath: '/app/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/reseller/': {
      id: '/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof ResellerIndexRouteImport
      parentRoute: typeof ResellerRoute
    }
    '/api/agent/ack': {
      id: '/api/agent/ack'
      path: '/api/agent/ack'
      fullPath: '/api/agent/ack'
      preLoaderRoute: typeof ApiAgentAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/heartbeat': {
      id: '/api/agent/heartbeat'
      path: '/api/agent/heartbeat'
      fullPath: '/api/agent/heartbeat'
      preLoaderRoute: typeof ApiAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/pull': {
      id: '/api/agent/pull'
      path: '/api/agent/pull'
      fullPath: '/api/agent/pull'
      preLoaderRoute: typeof ApiAgentPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/script': {
      id: '/api/agent/script'
      path: '/api/agent/script'
      fullPath: '/api/agent/script'
      preLoaderRoute: typeof ApiAgentScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cron/billing': {
      id: '/api/v1/cron/billing'
      path: '/api/v1/cron/billing'
      fullPath: '/api/v1/cron/billing'
      preLoaderRoute: typeof ApiV1CronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/kopokopo/$slug': {
      id: '/api/webhooks/kopokopo/$slug'
      path: '/api/webhooks/kopokopo/$slug'
      fullPath: '/api/webhooks/kopokopo/$slug'
      preLoaderRoute: typeof ApiWebhooksKopokopoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mpesa/$slug': {
      id: '/api/webhooks/mpesa/$slug'
      path: '/api/webhooks/mpesa/$slug'
      fullPath: '/api/webhooks/mpesa/$slug'
      preLoaderRoute: typeof ApiWebhooksMpesaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/radius/accounting/$slug': {
      id: '/api/v1/radius/accounting/$slug'
      path: '/api/v1/radius/accounting/$slug'
      fullPath: '/api/v1/radius/accounting/$slug'
      preLoaderRoute: typeof ApiV1RadiusAccountingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAcsRoute: typeof AppAcsRoute
  AppAiRoute: typeof AppAiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppFieldRoute: typeof AppFieldRoute
  AppHotspotRoute: typeof AppHotspotRoute
  AppImportRoute: typeof AppImportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppRadiusRoute: typeof AppRadiusRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoutersRoute: typeof AppRoutersRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcsRoute: AppAcsRoute,
  AppAiRoute: AppAiRoute,
  AppBillingRoute: AppBillingRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppFieldRoute: AppFieldRoute,
  AppHotspotRoute: AppHotspotRoute,
  AppImportRoute: AppImportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppRadiusRoute: AppRadiusRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoutersRoute: AppRoutersRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ResellerRouteChildren {
  ResellerIndexRoute: typeof ResellerIndexRoute
}

const ResellerRouteChildren: ResellerRouteChildren = {
  ResellerIndexRoute: ResellerIndexRoute,
}

const ResellerRouteWithChildren = ResellerRoute._addFileChildren(
  ResellerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResellerRoute: ResellerRouteWithChildren,
  ApiAgentAckRoute: ApiAgentAckRoute,
  ApiAgentHeartbeatRoute: ApiAgentHeartbeatRoute,
  ApiAgentPullRoute: ApiAgentPullRoute,
  ApiAgentScriptRoute: ApiAgentScriptRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1CronBillingRoute: ApiV1CronBillingRoute,
  ApiWebhooksKopokopoSlugRoute: ApiWebhooksKopokopoSlugRoute,
  ApiWebhooksMpesaSlugRoute: ApiWebhooksMpesaSlugRoute,
  ApiV1RadiusAccountingSlugRoute: ApiV1RadiusAccountingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
